### ISSUE TITLE
GHC 8.4.x compatibility

### ISSUE THREAD

**Issue by yairchu** [haskell-hvr/uuid#39] opened 2018-05-09 11:10 UTC
`uuid` doesn't work with GHC-8.4.x.

`uuid` currently depends on `entropy < 0.4` (0.3.8) which doesn't support GHC-8.4.x due to its setup script failing to parse `ghc-pkg`'s output.

Iiuc https://github.com/haskell-hvr/uuid/pull/36 attempts to fix this.

Currently this is work-aroundable using the `--allow-newer=entropy` cabal flag.

**Comment by hvr** [comment] 2018-05-14 06:58
Duplicate of #34

**Closed by hvr** 2018-05-14 06:58 UTC
