### ISSUE TITLE
Currently marked as unbuildable in Stackage

### ISSUE THREAD

**Issue by ocramz** [haskell-hvr/uuid#38] opened 2018-05-04 09:26 UTC
https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L493

**Comment by DanBurton** [comment] 2018-05-10 06:51
This is basically a dupe of #34. 

Here's a permalink that points to the correct location:

https://github.com/fpco/stackage/blob/ac4d4ff24e4b5e61982ae6b54852f3c8407dde90/build-constraints.yaml#L498

I updated the comment to reflect that this is because of `uuid`'s incompatibility with `entropy-0.4.*`. There used to be other reasons as well, but they have been resolved, and I believe this is the only one left.

**Comment by hvr** [comment] 2018-05-14 06:58
Duplicate of #34

**Closed by hvr** 2018-05-14 06:58 UTC
